/*

 BACKGROUND.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : C:\Users\Joe\Downloads\gbtd22\basicTileSet.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define backgroundWidth 40
#define backgroundHeight 18
#define backgroundBank 0

extern unsigned char background[];

/* End of BACKGROUND.H */
